POST http://localhost:4000/finances/createFinance
content-type: application/json

{
    "income": "1290000",
    "fixedExpenses": "500000", 
    "variableExpenses": "150000", 
    "savingsPlan": "200000"
}
